# Configuration for Warden service OpenAPI generation
version: v2

clean: false

managed:
  enabled: true

  disable:
    - module: buf.build/googleapis/googleapis
    - module: buf.build/bufbuild/protovalidate
    - module: buf.build/kratos/apis

  override:
    - file_option: go_package
      path: warden/service/v1
      value: github.com/go-tangra/go-tangra-warden/gen/go/warden/service/v1;wardenpb

inputs:
  - directory: protos
    paths:
      - protos/warden/service/v1

plugins:
  # generate openapi v3 yaml doc
  - local: protoc-gen-openapi
    out: cmd/server/assets
    opt:
      - naming=json
      - depth=2
      - default_response=false
      - enum_type=string
      - output_mode=merged
      - fq_schema_naming=false
